# Nixy listening port
port = "6000"
# X-Proxy header, defaults to hostname
xproxy = ""

# Drove API
#drove = ["http://localhost:10000"] # add all HA cluster nodes in priority order.
#drove = ["http://localhost:4000", "http://localhost:5000"] # add all HA cluster nodes in priority order.
drove = ["https://stg-nb6.drove.phonepe.com:443"] # add all HA cluster nodes in priority order.
event_refresh_interval_sec = 5
user = "" # leave empty if no auth is required.
pass = ""
access_token = "O-Bearer OLYMPUS_TOKEN"
# Nixy realm, set this if you want to be able to filter your apps (e.g. when you have different loadbalancers which should expose different apps)
# Put your subdomain here. It will be used to match the subdomain of the exposed apps
realm = "api.nixy.stg-drove.phonepe.nb6"

# Nginx
#nginxplusapiaddr="127.0.0.1"
nginxplusapiaddr="stg-nginx301.phonepe.nb6"

traefiklabel = "traefik.backend"
traefikbackend = ["nixy-demo"]
#nginxplusapiaddr = "10.57.11.218:2222"
maxfailsupstream = 0
failtimeoutupstream = "1s"
slowstartupstream = "0s"

# Statsd settings
#[statsd]
#addr = "10.57.8.171:8125" # optional for statistics
#namespace = "nixy.my_mesos_cluster"
#sample_rate = 100
leader_vhost = "drove.ssdev.test"

